### ISSUE TITLE
Intervals and timer buggy

### ISSUE THREAD

**Issue by TheOriginalJosh** [TheOriginalJosh/nativescript-slides#10]
Currently, the set interval worked but after going through the entire loop the animations start to get out of order.

also I think that if an interval is set it should automatically set the loop attr to true.

**Comment by Obsessive** [comment]
Yeah animation is going out of order but no need to set loop true if interval is set. It is fixed.

**Comment by TheOriginalJosh** [comment]
I the the animations being out of order have more to do with the next slide function and nothing to do with the intervals, on second thought

**Comment by TheOriginalJosh** [comment]
@Obsessive I want to add you as a collaborator on npm, what is  your username?

**Comment by Obsessive** [comment]
https://www.npmjs.com/~obsessive

**Comment by TheOriginalJosh** [comment]
I've decided to remove the intervals in favor the users being able to create their own now that there are working goto next slide and previous functions also along with current index and others. this will help cut down on the bloat fo the slides in an attempt to make them more maintainable and less error prone.
