### ISSUE TITLE
pageIndicators not displayed in TNS 3

### ISSUE THREAD

**Issue by toddanglin** [TheOriginalJosh/nativescript-slides#104]
It seems the `pageIndicators` are no longer being displayed in apps running TNS 3.0.

I confirmed in the demo app by upgrading the plugin and the demo to the latest versions of NativeScript and `tns-core-modules` (`3.1.0`). The demo runs fine, but the `pageIndicators` are not shown, in either iOS or Android.

I'll try to take a look at the underlying code and see if there's any "obvious" reason they may be missing. Logging the issue in case others have hit this and there is a known workaround.

**Comment by toddanglin** [comment]
OKAY...that was quick.

The problem appears to be related to the use of an old version of the `nativescript-dom` plugin. Upgrading to the latest version of this plugin (`2.0.0`), which is made to support TNS 3, fixes the problem.

SO...I guess simplest solution is to release a new version of this plugin that support TNS 3+ and includes these updated references. Maybe that's the plan?

**Comment by TheOriginalJosh** [comment]
@toddanglin shoot..., actually thought I had done this.  I'll update the reference in the package.json tonight.  Thanks man appreciate the heads up!

**Comment by TheOriginalJosh** [comment]
Dependency updated in this release. thanks again @toddanglin! https://github.com/TheOriginalJosh/nativescript-slides/releases/tag/2.2.10
