### ISSUE TITLE
Android - slide

### ISSUE THREAD

**Issue by c13andka** [TheOriginalJosh/nativescript-slides#110]
For me i can not slide on Android phone, but works perfect on iOS.

Any one else have this problem ?

**Comment by TheOriginalJosh** [comment]
@c13andka could please post an example of your code? if you have a listView or scrollview in the slides it can create a conflict.

**Comment by c13andka** [comment]
`	<TNSSlideContainer #slideCon class="slides" pageIndicators="true" row="1" [visibility]="isLoadingSlideshow || hasAppointment ? 'collapse' : 'visible'">

			<TNSSlide #startSlide class="slide-1">

				<GridLayout class="app-startpage-slide" horizontalAlignment="stretch" verticalAlignment="stretch" (tap)="goToNextSlide()">

					<GridLayout orientation="vertical" verticalAlignment="center" class="slide-text first" columns="2*, 2*" rows="auto, auto, *">
						<Label text="..." textWrap="true" class="header" col="0" colSpan="2" row="0"></Label>

						<Label horizontalAlignment="left" text="..." textWrap="true" class="description" col="0" row="1"></Label>
						<StackLayout orientation="vertical" horizontalAlignment="left" class="guide" col="0" row="2">
							<Label text="..." textWrap="true" class="description small"></Label>
						</StackLayout>
					</GridLayout>
				</GridLayout>

			</TNSSlide>

			<TNSSlide class="slide-2">
				<GridLayout class="app-startpage-slide" horizontalAlignment="stretch" verticalAlignment="stretch" (tap)="goToNextSlide()">
					
					<StackLayout orientation="vertical" verticalAlignment="center" class="slide-text">

						<GridLayout class="circle" verticalAlignment="center" [visibility]="hideSlideshowIcons ? 'collapse' : 'visible'">
							<Label text="&#xf274;" class="fontawesome-icon" verticalAlignment="center"></Label>
						</GridLayout>

						<Label text="..." textWrap="true" class="header" verticalAlignment="center"></Label>
						<Label text="...." textWrap="true" class="description medium"></Label>
						<Label text="..." textWrap="true" class="description small"></Label>

					</StackLayout>

				</GridLayout>
			</TNSSlide>

			<TNSSlide class="slide-3">
				<GridLayout class="app-startpage-slide" horizontalAlignment="stretch" verticalAlignment="stretch" (tap)="goToNextSlide()">
					
					<StackLayout orientation="vertical" verticalAlignment="center" class="slide-text">

						<GridLayout class="circle" verticalAlignment="center" [visibility]="hideSlideshowIcons ? 'collapse' : 'visible'">
							<Label text="&#xf03d;" class="fontawesome-icon" verticalAlignment="center"></Label>
						</GridLayout>

						<Label text="..." textWrap="true" class="header" verticalAlignment="center"></Label>
						<Label text="..." textWrap="true" class="description medium"></Label>
						<Label text="..." textWrap="true" class="description small"></Label>

					</StackLayout>

				</GridLayout>
			</TNSSlide>

		</TNSSlideContainer>`


i have attached tap on every slide so i can tap for next slide. The strange thing is that if a have console.log inside the slider method in the packade, it will only be called on the last slide. So the last slide works with sliding. But not the two first

**Comment by TheOriginalJosh** [comment]
@c13andka I haven't  been actively supporting this plugin for angular I built https://github.com/TheOriginalJosh/nativescript-ngx-slides specifically for that use case.  You should be able to swap out the plugins pretty seamlessly.  Going to close this issue for now, I'm going to close this issue for now but if you have the same issue with NGX-slides don't hesitate to open an issue.
