### ISSUE TITLE
ERROR TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by HartzDev** [TheOriginalJosh/nativescript-slides#114]
hello guys,
iam still new in nativescript+angular. and now iam developing an app that need use slide.
and every time i slide , i have to change color of indicator. and i wanna get current index of what slide i am at.

this is my Html :
 <Slides:SlideContainer angular="true" #slides pageIndicators="true" pagerOffset= "75%" (changed)="OnChange()">
        <Slides:Slide class="slide-1" style="background-color: #fff" >
            <StackLayout>
                <Image class="logo1" src="~/images/logo_1.png" width="23%" height="15%" stretch="fill" horizontalAlignment="center"></Image> 
                <Image src="~/images/logo_3.png" stretch="fill" width="88%" height="15%" horizontalAlignment="center"></Image> 
                <Button class="btnLogin1" width="88%" text="Login" verticalAlignment="bottom" (tap)="btnClicked()"></Button>
            </StackLayout>
        </Slides:Slide> 
        <Slides:Slide class="slide-2" style="background-color: #4B4BA6"> 
                <Image class="banner2" src="~/images/login_banner_2.png" stretch="fill" width="88%" height="70%" horizontalAlignment="center"></Image> 
                <Button class="btnLogin1" width="88%" text="Login" verticalAlignment="bottom"></Button>
        </Slides:Slide> 
        <Slides:Slide class="slide-3" style="background-color: #E52C4B">
            <Image class="banner2" src="~/images/login_banner_3.png" stretch="fill" width="88%" height="70%" horizontalAlignment="center"></Image> 
            <Button class="btnLogin1" width="88%" text="Login" verticalAlignment="bottom"></Button>

        </Slides:Slide>
        <Slides:Slide class="slide-4" style="background-color: #E06734">
                <Image class="banner2" src="~/images/login_banner_4.png" stretch="fill" width="88%" height="70%" horizontalAlignment="center"></Image> 
                <Button class="btnLogin1" width="88%" text="Login" verticalAlignment="bottom"></Button>
    
            </Slides:Slide>
    </Slides:SlideContainer>

and this is my .ts :
import { Component, ElementRef, OnInit, ViewChild } from "@angular/core";
import {registerElement} from "nativescript-angular/element-registry";
import { Page } from "ui/page";
import * as slide from 'nativescript-slides/nativescript-slides'

registerElement("Slide", () => require("nativescript-slides").Slide);
registerElement("SlideContainer", () => require("nativescript-slides").SlideContainer);

@Component({
    selector: "LoginPage",
    moduleId: module.id,
    templateUrl: "./login-page.component.html",
    styleUrls: ["./login-page.component.css"]
})
export class LoginPageComponent implements OnInit {

    @ViewChild("slides") slides: ElementRef;    

    constructor(private page : Page) {
        /* ***********************************************************
        * Use the constructor to inject app services that you need in this component.
        *************************************************************/
        page.actionBarHidden=true;
    }

    ngOnInit(): void {
        /* ***********************************************************
        * Use the "ngOnInit" handler to initialize data for this component.
        *************************************************************/
    }

    OnChange(args){
        let slideContainer = <slide.SlideContainer>args.object; <-- this trigger the error
        console.log(slideContainer.currentIndex); 
    }

    btnClicked(){
        console.log("tab!!!");
    }

    ngAfterViewInit() {
        let SlidesXml = this.slides.nativeElement;
        SlidesXml.constructView();
    }    
}

thx.

**Comment by TheOriginalJosh** [comment]
Hi @HartzDev, For angular usage please check out the package nativescript-ngx-slides. it's made specifically for angular.

https://www.npmjs.com/package/nativescript-ngx-slides
