### ISSUE TITLE
Changing slides really fast seems to lose the currentPanel 

### ISSUE THREAD

**Issue by bradmartin** [TheOriginalJosh/nativescript-slides#27]
Changing the slides really fast, I'm able to get the error:

`Cannot read property 'right' of undefined.` on line *61* of the transpiled nativescript-slides.js file. Which points to `currentPanel`

I haven't tried going to the previous but assuming the same event will occur.

**Comment by TheOriginalJosh** [comment]
this is fixed in 1.5.2
