### ISSUE TITLE
Feature Request: Slide Change Event

### ISSUE THREAD

**Issue by shripalsoni04** [TheOriginalJosh/nativescript-slides#29]
I think currently we don't have any way to know when slide is changed. It will be very good if we have an event whenever slide is changed to satisfy scenarios like changing state of some controls, which are not inside slide, depending on active slide.

After having a quick look at code, I think we can call `notify`at the end of `setupPanel` method like this:
```
private setupPanel(panel: ISlideMap) {
    ...
    this.setActivePageIndicator(this.currentPanel.index);
    this.notify({
	    eventName: 'slideChanged',
	    object: new Observable({currentPanel: this.currentPanel})
    });
}
``` 

What do you think?

**Comment by TheOriginalJosh** [comment]
@shripalsoni04 I was looking into this, I'm not familiar with the notify function, but do we need the object to be an observable or can it just be the currentPanel object?

**Comment by shripalsoni04** [comment]
Notify function is used to emit custom events. As per the [documentation of custom events](https://docs.nativescript.org/core-concepts/events#creating-a-custom-event), notify method takes the implementor of [_EventData Interface_](http://docs.nativescript.org/api-reference/interfaces/_data_observable_.eventdata.html) as an argument. This _EventData Interface_ only accepts `observable` as the `object` value.

Though I have tried to send a plain object as an `object` value in `notify` function, it is also working properly without any issue.

But, I think we should send `observable` as `object` value in `notify` method so that any future change in event mechanism of nativescript do not break this.

**Comment by TheOriginalJosh** [comment]
Hi @shripalsoni04 @sitefinitysteve end up adding these going above and beyond and adding a couple other events. It's merged now and I should have it published to npm this evening.  :+1:

**Comment by TheOriginalJosh** [comment]
https://github.com/TheOriginalJosh/nativescript-slides/pull/36
