### ISSUE TITLE
Orientation bug and loop right not working properly

### ISSUE THREAD

**Issue by Paulsonps** [TheOriginalJosh/nativescript-slides#32]
Orientation: line 256                   // absolute_layout_1.AbsoluteLayout.setTop(_this._footer, topOffset);

**Comment by TheOriginalJosh** [comment]
Hi @Paulsonps thanks for the info, was able to recreate the orientation crashing, could you expand on how the loop right is not working properly?

**Comment by Paulsonps** [comment]
Hi @JoshSommer   see i have 6 slides 1 to 6 when i click slide 6 next slide
 should be first one but now what happened is after slide 6 it is not going
slide 1 if i want to come slide one i have to click or swipe prev slide
after slide 6 next click or swipe is not working... i think you will get
it...

**Comment by TheOriginalJosh** [comment]
@Paulsonps thanks again for the info is this happening on iOS or Android or Both?

**Comment by Paulsonps** [comment]
@Josh Sommer,

 Now i am working on android i didn't start rum my app on ios sorry

 Thanks

**Comment by TheOriginalJosh** [comment]
Should be fixed in the 1.7.0 release. re-open if it's still an issue. Thanks @Paulsonps
