### ISSUE TITLE
Changed event not getting triggered on manual call

### ISSUE THREAD

**Issue by shripalsoni04** [TheOriginalJosh/nativescript-slides#40]
Thanks for implementing events on various slide states.

Events are getting triggered properly when we swipe the slides. But if we call `nextSlide` or `previousSlide` functions manually, `changed` event is not getting triggered.

I think we need to emit `changed` event in `nextSlide` and `previousSlide` functions also.

**Comment by TheOriginalJosh** [comment]
Should be fixed in the 1.7.0 release thanks to @sitefinitysteve. Thanks for everything guys :D
