### ISSUE TITLE
Indicators doesn't show up

### ISSUE THREAD

**Issue by levipadre** [TheOriginalJosh/nativescript-slides#43]
Thank you for the plugin, it's really cool.
I noticed that the page indicators disappear on my iPhone 5s.
It blinks for a sec, but after nothing.

Do you know what can be the problem?

Thanks

**Comment by TheOriginalJosh** [comment]
@levipadre Thanks for the feedback, could you tell me if you're using it in vanilla NativeScript or ng2?

**Comment by levipadre** [comment]
It's a learning curve this project for me, so I'm not quite sure what you mean, sorry.
But I'm using typescript if that wad the question.
In emulator it's working well, but on phone appears-disappears randomly.

**Comment by TheOriginalJosh** [comment]
hmm, I actually don't have an apple developers license so I've never been able to test on an actual device, I'll try to figure something out here.

Essentially I was wondering if you're using Angular or not. If you ever need any help with other stuff check out the NativeScript Slack channel lots of helpful people there too

**Comment by levipadre** [comment]
Thank you for the advice and effort. Some help would be great.
Cheers

**Comment by TheOriginalJosh** [comment]
@levipadre  I've published a new version of the slide to npm under the beta tag. I refactored how the indicators are done and I would be  interested in your feedback if this is still an issue, in this version. Hope your project is going well and thanks for the feedback.
