### ISSUE TITLE
Feature request: gotoSlide(index)

### ISSUE THREAD

**Issue by lillebak** [TheOriginalJosh/nativescript-slides#47]
Hi

I pretty new here and I couldn't find another place to send a feature request.

I am very happy to use your plugin and we are currently using it for showing images. Currently we are navigating from a page with thumbnails, which means that the user can click a thumbnail and I navigate to the slides. It would therefor be nice to be able to open the specific image that the user clicked by using some kind of gotoSlide command.

Or maybe the existing next command could be reused and take a parameter with slide index:
slideContainer.nextSlide(slideIndex);

Have you thought about something like this before?

BR / Jens Peter

**Comment by TheOriginalJosh** [comment]
@lillebak Hey thanks for the feed back, I'm currently working a a 2.0 version and will make sure to include that.

**Comment by lillebak** [comment]
Sounds great.

Is the release date in the near future?

**Comment by lillebak** [comment]
Sorry, I didn't mean to close it. I think I hit the wrong button in my comment before :-)

**Comment by TheOriginalJosh** [comment]
Lol no worries.  Honestly I'm not sure,  I'm trying to take my time and get it right, i have a couple milestones I need to complete before I release.

**Comment by dkallkro** [comment]
The gotoSlide(index) would be really nice. We have an upcoming release where we are planning to use this plugin. (release within 1 week or so) will this feature make that? we cross our fingers. 👍

**Comment by TheOriginalJosh** [comment]
I was thinking about how to implement this and I was wonder what your thoughts on how it should behave. Basically it boils down to should the slides slide by until you reach the one you specified or should they just jump to the slide.i m leaning towards the the first even though the latter of the two would be easier.

**Comment by dkallkro** [comment]
It should just JUMP to the slide.

**Comment by TheOriginalJosh** [comment]
@dkallkro when you say jump, do you mean that slide just appears?

**Comment by dkallkro** [comment]
yes, just appear.... we use it as a image gallery., so it like clicking a image on our imagelist page. and then we are navigated to that image.

**Comment by TheOriginalJosh** [comment]
@dkallkro I just published a version to npm under the beta tag. I includes `goToSlide` that accepts an index. You can use like `slideContainer.goToSlide(2)` for example. if you can give it a shot and let me know what you think I would appreciate it.

**Comment by lillebak** [comment]
I just tested the new version 2.1.0. The new gotoSlide() function works great. Thanks! :)

But for some reason I am not able to receive any events from the SlideContainer. Have you noticed anything like this? I am especially dependent on the CHANGED_EVENT.

**Comment by TheOriginalJosh** [comment]
Hi @lilleback is this only when using the gotoSlide function, or all events now?

**Comment by dkallkro** [comment]
@TheOriginalJosh just for your info. @lilleback is working with me and are doing the testing. :)

**Comment by lillebak** [comment]
I will do my best to test it :) 
It seems that all events has stopped working. I just tested them this morning. I also tried debugging the the slides plugin and it seems that the following function in code is reached and that it tries to call notify, but notify does not trigger an event as it should. Not sure why.

	private triggerChangeEventLeftToRight() {
		this.notify({
			eventName: SlideContainer.CHANGED_EVENT,
			object: this, 
			eventData: {
				direction: direction.left,
				newIndex: this.currentPanel.index,
				oldIndex: this.currentPanel.index + 1
			}
		});
	}

**Comment by TheOriginalJosh** [comment]
@lillebak and @dkallkro  I've added a new event notification specifically for the `goToSlide` function. Let me know if this works for you better. it should be published to NPM under the beta tag.

**Comment by lillebak** [comment]
Hi @TheOriginalJosh 

The new change event in the gotoSlide function does not work either. 

I thought that something might be wrong with my TNS installation or project, so I decided to downgrade nativescript-slides to 1.7.1, which is the version that I can remember worked for certain.  After the downgrade, all the events works again. I then upgraded to 2.0.1 and then the events stopped working again.

Could it be something in the cleanup that was made in 2.0.1?

**Comment by TheOriginalJosh** [comment]
@lillebak Are you testing in iOS or Android? last night when I tested in iOS I was getting events. Could I see a sample of your code that is using the events?

**Comment by lillebak** [comment]
This is the XML:

```
      <Slides:SlideContainer row="0" id="slides" androidTranslucentStatusBar="false" pageIndication="false" loaded="onSlideContainerLoaded" start="onStart" cancelled="onCancelled" changed="onChanged" finished="onFinished" >
      </Slides:SlideContainer>

```
And this is the controller js file that handles the changed event:

```
exports.onChanged = function (args){
	var data = args.eventData;
	console.log("######################## Changed event: " + JSON.stringify(data));
    model.set("currentSlideIdx", data.newIndex);
    viewCurrentSlide();
};
```

**Comment by lillebak** [comment]
@TheOriginalJosh - By the way i am running it on ios emulator. I will try and clone a fresh project and run the demo app of yours to test if that also fails on 2.0.1.

**Comment by lillebak** [comment]
The demo is also not receiving the events on 2.0.1. I also tried it on android which gives the same problem.

**Comment by erjdriver** [comment]
+1 on the .gotoSlide() feature request.

Also another one would be to slide vertically - up and down 1 slide/card at a time.

Thanks.

**Comment by TheOriginalJosh** [comment]
I'm going to close this since gotoslide is in place
