### ISSUE TITLE
Strange behaviour with interval, finished event, and disablePan="true"

### ISSUE THREAD

**Issue by Ed-Dikotope** [TheOriginalJosh/nativescript-slides#48]
When I try setting the interval, `interval="2000"` and I have say 3 slides, then on my `changed` event I count the indexes and expect to see 0, 1, 2 and have the `finished` event handler fire... none of that seems to happen.

The app starts and the indexes log as 0,1, but I do see the slides quickly move from slide 1 - 3. When I set disablePan="false", then the indexes and slides show up correctly as 0,1,2 (1,2,3). I think the timer is buggy.

But my use case is to have the app start with an image slider, with `disablePan=true`, and `interval=2000` then on finished event, have a ‘main' page show up

**Comment by TheOriginalJosh** [comment]
@Ed-Dikotope I have a beta version of the slides up on npm it actually removes the intervals infavor of the user adding their own setInterval. if you want to give it a try it's published to npm under the beta tag.
