### ISSUE TITLE
Feature Request: event when slides are disposed

### ISSUE THREAD

**Issue by bradmartin** [TheOriginalJosh/nativescript-slides#5]
Need an event when the slides are "complete" or "done" internally. This way we can reset the android status bar, also exposing a callback to the devs for done with slides (like Finish) would be good to navigate to a different part of the app.

**Comment by TheOriginalJosh** [comment]
That's a great idea, we should also unbinded any remaining pan events there as well. Do you have an example somewhere how this it done?

alternatively what about exposing a `dispose` function that devs could call that would reset these status bar an unbind any events?
