### ISSUE TITLE
Adding a Slide Dynamically Except loaded

### ISSUE THREAD

**Issue by TeorikDeli** [TheOriginalJosh/nativescript-slides#51]
Hi!

I cannot add new slides to my slide container dynamically like onTap or after a specific slide. How can I do that?

Thanks.

**Comment by TheOriginalJosh** [comment]
@TeorikDeli Currently this isn't something that is supported in the slides, possibly in the future.  Sorry for the long delay in getting back to you.

**Comment by poorcoder** [comment]
Can you add this adding on thy fly future...
