### ISSUE TITLE
Wrong newIndex value in changed event argument on nextSlide call

### ISSUE THREAD

**Issue by shripalsoni04** [TheOriginalJosh/nativescript-slides#53]
When we call `nextSlide` or `previousSlide` method, and if we have attached listener to `changed` event, the values of `newIndex` and `oldIndex` in the event argument are coming wrong.

After looking into the code, I found that in `nextSlide` method, `this.triggerChangeEventLeftToRight();` should be changed to `this.triggerChangeEventRightToLeft();`(as on nextSlide, actually the slide is moving from rightToLeft) and similar change in `previousSlide` method.

**Comment by TheOriginalJosh** [comment]
I'll have these swapped in the next release. thank you for the heads up!

**Comment by TheOriginalJosh** [comment]
I have the 2.0 version of slides published to npm under the beta tag. this should be fixed in it.  If it's still problem let me know. Thanks again for letting me know of this issue.
