### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by simkepal** [TheOriginalJosh/nativescript-slides#56]
Hello,

I want to try this out but I can't install this script. I run npm install nativescript-slides

And this is response I get.

Registry returned 404 for GET on https://registry.npmjs.org/nativescript-dev-nativescript-slides

What am I doing wrong.

Thank you!

**Comment by TheOriginalJosh** [comment]
Hi @simkepal, that should work for you, donyou have the same problem installing other plugins?

**Comment by TheOriginalJosh** [comment]
I'm going to close this issue for the time being but if you keep having troubles let me know, I'll try to help as best I can.
