### ISSUE TITLE
Getting file not found error

### ISSUE THREAD

**Issue by erjdriver** [TheOriginalJosh/nativescript-slides#59]
I installed this plugin into my {N} project.

tns plugin add git-url

and I see it installed fine under node_modules folder - v2.0.1

Created a simple xml file and am getting follow exception when I run - test4 is the name of my project.

`Error: Building UI from XML. @file:///app/main-page.xml:50:2
 ���Module '/data/data/org.nativescript.test4/files/app/nativescript-slides' not found for element 'nativescript-slides:SlideContainer'.
   ���com.tns.NativeScriptException: Failed to find module with absolute path: "/data/data/org.nativescript.test4/files/app/nativescript-slides".
      com.tns.Module.resolvePathHelper(Module.java:220)
    com.tns.Module.resolvePath(Module.java:60)
`

**Comment by erjdriver** [comment]
I think this is operator error

i need to do "tns plugin add nativescript-slides"

case closed.

**Comment by TheOriginalJosh** [comment]
Ah no worries, happens to the best of us. let me know if you have any more problems
