### ISSUE TITLE
Android status bar isn't turning transparent, white instead.

### ISSUE THREAD

**Issue by TheOriginalJosh** [TheOriginalJosh/nativescript-slides#6]
With the new android transparent status bar i'm getting a white bar. Android Marshmellow, Nexus 5x
![screenshot_20160519-062559](https://cloud.githubusercontent.com/assets/1486275/15390766/9f43ab72-1d8b-11e6-90d3-24b1c1f77f11.png)

**Comment by bradmartin** [comment]
Think I might have accidentally removed a few key lines :scream:

**Comment by Obsessive** [comment]
![screenshot_20160519-194711](https://cloud.githubusercontent.com/assets/17127448/15396672/bb19491e-1dfa-11e6-80bf-2df708f6a405.png)


Is this how you want the actionbar to look like?

**Comment by Obsessive** [comment]
sorry not actionbar i mean statusbar

**Comment by bradmartin** [comment]
const View = android.view.View;
​
			let window = app.android.startActivity.getWindow();
			// set the status bar to Color.Transparent
			window.setStatusBarColor(0x000000);
​
			let decorView = window.getDecorView();
			decorView.setSystemUiVisibility(
				View.SYSTEM_UI_FLAG_LAYOUT_STABLE
				| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
				| View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
				// | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION // hide nav bar
				// | View.SYSTEM_UI_FLAG_FULLSCREEN // hide status bar
				| View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);
		

Yea this is what I forgot. On phone now or I'd make a PR. there's also a function needed to pad the first child view the height of the statusbar.

**Comment by bradmartin** [comment]
I have the function to do that on my pc. I can fix later.

**Comment by bradmartin** [comment]
I wanted to add a hideStatusBar option too but we need an event to be called when the slides are done so we can show the status bar again.

**Comment by Obsessive** [comment]
I did something similar but what you did looks better than mine.

**Comment by Obsessive** [comment]
If you hide nav bar will it slide into screen when i interact with the screen

**Comment by bradmartin** [comment]
Yea if you touch the bottom or swipe it up, it will animate in for the
default android time and then go away. Similar to full screen YouTube
videos or what most games do. That's considered 'immersive' mode. I blogged
about it months ago.

**Comment by bradmartin** [comment]
On iOS I need to check how to hide the statusbar I made an attempt last
night but I likely forgot to update the plugin code in the test app :) got
the one liner from one of the statusbar plugins (PeterStaev's).  So ideally
if I can get that working then we can have the hideStatusBar option.
Android transparent option (gotta pad the first child view in the slides)
and then maybe a full screen mode that hides both on android and the
statusbar on iOS.

**Comment by bradmartin** [comment]
More I think about it we maybe should just provide good samples even using other plugins. Burke has the statusbar plugin that allows you to change the color. Less work on this plugin and doesn't make it crazy with options

**Comment by bradmartin** [comment]
I can put some good android intro samples together later to show off how easy it is. Without adding more and more options to this plugin. What do you guys think?

**Comment by TheOriginalJosh** [comment]
That would be cool dude!

**Comment by TheOriginalJosh** [comment]
Use the slides for tutorials. Maybe make o
An official NativescriptSnacks app.lol

**Comment by bradmartin** [comment]
Close my man :smile:

**Comment by TheOriginalJosh** [comment]
😉
