### ISSUE TITLE
v2.1.3 - events not being called

### ISSUE THREAD

**Issue by erjdriver** [TheOriginalJosh/nativescript-slides#61]
The slider seems to be working except callback events don't seem to be called.

I see the internal debug message "changed active 0"...

This is in my ts file

`export function onStart()
{
    console.log( "onStart ");
} 
`

in my xml file

`	<Slides:SlideContainer id="slides" row="0" start="onStart" pageIndicators="false" loop="false">
`

**Comment by erjdriver** [comment]
What does 'help wanted' mean - want me to send something?

**Comment by TheOriginalJosh** [comment]
Hi @erjdriver I had just tag it as that someone else is going to look into it here.   no worries

**Comment by TheOriginalJosh** [comment]
I believe the events should be firing now let me know if they are not.
