### ISSUE TITLE
Slider not working when slides are added programatically on iOS (probably on Android as well)

### ISSUE THREAD

**Issue by terreb** [TheOriginalJosh/nativescript-slides#63]
The slider doesn't work for me when I add slides programatically.
tns-ios: 2.1.1
tns-android:2.1.1
tns-core-modules: 2.1.0
nativescript-slides: 2.1.4
Simulator: iPhone 6 iOS 9.3

XML:

```
    <Page xmlns="http://schemas.nativescript.org/tns.xsd"
      xmlns:Slides="nativescript-slides" 
      loaded="onLoaded">

  <GridLayout>
      <Slides:SlideContainer id="slider" width="100%" height="100%">
          <Slides:Slide backgroundColor="red">
            <Label text="Slide 0"/>
          </Slides:Slide>
      </Slides:SlideContainer>
  </GridLayout>
</Page>
```

JS:

```
 var labelModule = require('ui/label');
 var slides = require('nativescript-slides/nativescript-slides');

function onLoaded(args) {
    var page = args.object
    var sliderContainer = page.getViewById('slider');

    for (var i = 0; i < 10; i++) { 
        var slide = new slides.Slide();
        slide.width = '100%';
        slide.height = '300';
        slide.backgroundColor = 'red';
        var label = new labelModule.Label();
        label.text = 'Slide ' + (i+1);
        slide.addChild(label);
        sliderContainer.addChild(slide)
    }
}
exports.onLoaded = onLoaded;
```

**Comment by terreb** [comment]
Ok, I got more info on this. This happens when I add slides inside the page loaded event function. If I do the same inside the slider loaded event function like in your example all is working. This is weird, because page loaded event is fired after all other views are loaded. sliderContainer.isLoaded=true after the page loaded event. Could you comment on why is that? Thank you.

**Comment by andreasotto** [comment]
+1 +1 +1 +1 +1

**Comment by hairen** [comment]
>layoutPlaceHolder.addChild(slideContainer);

@toddanglin The above code cannot be compiled, getting an error message - error TS2339: Property 'addChild' does not exist on type 'View'. 

Did you miss other points in your above reply?

**Comment by toddanglin** [comment]
That should just be a TypeScript warning...your app should still work fine at runtime.

If you want to eliminate the warning, you just need to "type cast" the placeholder element. So, assuming you're using a StackLayout as the placeholder, you could do this:

```typescript
import { StackLayout } from "ui/layouts/stack-layout";

let layoutPlaceHolder = <StackLayout>page.getViewById("stacklayoutPlaceHolderForYourSlider");
```

**Comment by TheOriginalJosh** [comment]
@toddanglin thanks man
