### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new viewClass()')    

### ISSUE THREAD

**Issue by ahmedelgendy** [TheOriginalJosh/nativescript-slides#64]
Hello 
I am using the angular example as you said but I am facing this error:
`class ListComponent - inline template:1:8                                   
        ORIGINAL EXCEPTION: TypeError: undefined is not a constructor (evaluating 'new viewClass()')                       
        ORIGINAL STACKTRACE:                                                                                               
        createAndAttach@file:///app/tns_modules/nativescript-angular/view-util.js:90:33  `

My code:
```
import {Component,ElementRef, OnInit, ViewChild} from "@angular/core";
import {registerElement} from "nativescript-angular/element-registry";
registerElement("Slide", () => require("nativescript-intro-slides").Slide);
registerElement("SlideContainer", () => require("nativescript-intro-slides").SlideContainer);

@Component({
    moduleId: module.id,
    selector: "List-page",
    template: `
        <SlideContainer angular="true" #slides>
            <Slide *ngFor="let img of images">
                <Label [text]="img.title"></Label>
            </Slide>
        </SlideContainer>
    `
})

export class ListComponent implements OnInit {
    public images: Array<any> = [];
    @ViewChild("slides") slides: ElementRef;
    ngOnInit() {
        this.images.push({title: 'Sports'});
        this.images.push({title: 'Cats'});
        this.images.push({title: 'Food'});
    }
    ngAfterViewInit() {
        let SlidesXml = this.slides.nativeElement;
        SlidesXml.constructView();
    }
}
```
plus I could not find the method constructView.
Thank you

**Comment by TheOriginalJosh** [comment]
Hi @ahmedelgendy  I notice it pointing to the old project name of `nativescript-intro-slides` that is probably a problem. I would upgrade to the `nativescript-slides` project and it should have better compatibility.

let me know if this is still a probablem though, I haven't had a lot of success with the slides in angular myself but I haven't tried recently

**Comment by ahmedelgendy** [comment]
Thanks for your concern @TheOriginalJosh  now it works normal but indicators don't work

**Comment by TheOriginalJosh** [comment]
Hi @ahmedelgendy glad to here it's working(for the most part) the latest version of the slides lets you set the indicator styles with css have you done that?

**Comment by ahmedelgendy** [comment]
Ok thank you! @TheOriginalJosh
