### ISSUE TITLE
Feature request: custom slider width

### ISSUE THREAD

**Issue by terreb** [TheOriginalJosh/nativescript-slides#65]
Right now the slide take 100% of the screen, no matter what I set in css and without respecting the Slide Container wrapper width (please correct me if I'm wrong). I.e. if I put SlideContainer inside another view which is say 50% of the screen width, slides still take 100% width. Would be nice to have the slider to respect the width of the parent or have an option to set custom width explicitly.

**Comment by TheOriginalJosh** [comment]
Thanks @terreb  great feedback,I appreciate it. I don't believe this should be hard to change.

**Comment by terreb** [comment]
@TheOriginalJosh no problem and thank you for the great job and supper useful plugin!

**Comment by TheOriginalJosh** [comment]
I have this working on Android, clipping seems to not want to be cooperating on iOS currently.
