### ISSUE TITLE
property disablePan not applyied programmatically

### ISSUE THREAD

**Issue by developper89** [TheOriginalJosh/nativescript-slides#70]
i'm using nativescript ng and everything works fine except disabling/enabling the pan property on change event ,even after calling `constructView()`
was it meant to act like that ? is there another way ?

**Comment by developper89** [comment]
ok i figured out why, could you make the `applySwipe() ` method public or change the way the handler is attached in the next release ?

**Comment by TheOriginalJosh** [comment]
Sure, sorry for the delay in this I'll have an update publish in the next hour or two with apply swipe public.
