### ISSUE TITLE
Ios 10, xcode 8

### ISSUE THREAD

**Issue by moreaup** [TheOriginalJosh/nativescript-slides#73]
Hey guys,

Nativescript-slides doesn't seems to work since we are on Ios 10.
Did you know about that ? Are you on it ?

Thanks ! :)

**Comment by TheOriginalJosh** [comment]
Hey @moreaup thanks for the heads up, I've heard there is some issues with ios 10 support in {N} maybe that is the cause of this? if I have a chance I'll try upgrading to 2.3 tonight.

**Comment by moreaup** [comment]
Thanks @TheOriginalJosh, let me know !

**Comment by moreaup** [comment]
Any update ?

**Comment by TheOriginalJosh** [comment]
@moreaup sorry, haven't heard anything from anyone else, and I haven't updated to ios 10 yet. although i will be this week. 

Still having issues?

**Comment by TheOriginalJosh** [comment]
http://fluentreports.com/blog/?p=401 relevan info

**Comment by TheOriginalJosh** [comment]
Hey @moreaup , Sorry this has taken so long for me to get to.

I've updated some dependencies and the slides project and the demo is working for me again with Xcode 8 installed. 

the latest version *should work for you please let me know if not.
