### ISSUE TITLE
Indicators are not shown

### ISSUE THREAD

**Issue by codeback** [TheOriginalJosh/nativescript-slides#77]
I can't get page indicators to work. 

```
<GridLayout rows="200, auto, auto, auto" cols="*, auto">
    <SlideContainer angular="true" pageIndicators="true" loop="true" #slides row="0">
        <Slide *ngFor="let img of images">
            <Image [src]="img.source" stretch="aspectFill"></Image>
        </Slide>
    </SlideContainer>
...
```

Any idea of what I am doing wrong?

**Comment by TheOriginalJosh** [comment]
Good Morning @codeback  with the 2.0.0 release of the slides turning on the slides isn't' enough. you need to add to your app.css file to style the.
```
.slide-indicator-inactive{
    background-color: #fff;
    opacity : 0.4;
    width : 10;
    height : 10;
    margin-left : 2.5;
    margin-right : 2.5;
    margin-top : 0;
    border-radius : 5;
}

.slide-indicator-active{
    background-color: #fff;
    opacity : 0.9;
    width : 10;
    height : 10;
    margin-left : 2.5;
    margin-right : 2.5;
    margin-top : 0;
    border-radius : 5;
}
```

**Comment by codeback** [comment]
Sorry @TheOriginalJosh, I've forgot to say that I had added these css lines. 

I think is an angular related problem. I've solved this problem putting these lines in the general css file.

If I write these lines in the angular css file component ( styleUrls: [my-component.css] ) it doesn't work. But if I put these lines in a general css file it works.

 Thanks.

**Comment by TheOriginalJosh** [comment]
Cool, this is good to know I haven't used the Slides with angular. Thanks for feedback @codeback!

Cheers!
