### ISSUE TITLE
Slide indicator is now displayed vertically instead horizontally (2.2.2 vs 2.2.1)

### ISSUE THREAD

**Issue by creambyemute** [TheOriginalJosh/nativescript-slides#78]
Hey,

After removing platforms/ and node_modules/ folder and rebuilding our app from "scratch" I noticed that the slider indicator is now no longer displayed horizontally but vertically on the latest version (2.2.2).

I downgraded to 2.2.1 and there it's horizontally again.

Is this a bug or can I set the layout orientation somehow on 2.2.2 so it's horizontally instead of vertically again?

Cheers,

**Comment by TheOriginalJosh** [comment]
Oops that's completely a bug. is it happening on both platforms?

**Comment by creambyemute** [comment]
Yes, I experienced it on both Android and iOS

**Comment by TheOriginalJosh** [comment]
This is fixed in the latest release sorry it's taken so long. Thank you again for reporting it @creambyemute
