### ISSUE TITLE
automatically rotate slides

### ISSUE THREAD

**Issue by cindy-m** [TheOriginalJosh/nativescript-slides#79]
I implemented the slider with a few pictures. At the moment the pictures are first static until the user decides to slide them. So I was wondering it  it is possible  to let the slides rotate automatically (a sort of slideShow)??

**Comment by TheOriginalJosh** [comment]
Hi @cindy-m, what you could do is set an interval to call the `.next()` every few seconds.

**Comment by cindy-m** [comment]
you mean something like this: 
ngAfterViewInit() {
    var SlidesXml = this.slides.nativeElement;
    // SlidesXml.constructView();
    setInterval(() => {
      SlidesXml.nextSlide();
    }, 100);
  }

??
I am really new to nativescript (in combination with angular2), so I was wondering what the right way is to do set the interval

**Comment by cindy-m** [comment]
Got it working :D Thanks a lot :D :D

**Comment by TheOriginalJosh** [comment]
Awesome! 💃

**Comment by matheusabr** [comment]
If anyone needs in a plain JS, just follow this code:
```
slideContainer = page.getViewById('slideContainer')
  setInterval(function () {
    slideContainer.nextSlide()
  }, 4000)
```
