### ISSUE TITLE
devDependency to @next in the package.json is preventing publishing for iOS

### ISSUE THREAD

**Issue by NickIliev** [TheOriginalJosh/nativescript-slides#81]
Related to [https://github.com/NativeScript/NativeScript/issues/3046](https://github.com/NativeScript/NativeScript/issues/3046)

when creating app with the plugin with
`tns publish ios AppleUser ApplePass`

the plugin is causing duplicate files to be generated in the build package.
Issue noticed when using npm 3.x and should be fixed out of the box with 2.4.0.

Meanwhile, to prevent this behaviour it would be best to update the plugin package.json not to refer to @next versions.

[https://github.com/TheOriginalJosh/nativescript-slides/blob/master/package.json#L77](https://github.com/TheOriginalJosh/nativescript-slides/blob/master/package.json#L77)

**Comment by TheOriginalJosh** [comment]
this has been published. thanks again @NNieto I really appreciate it.
