### ISSUE TITLE
goToSlide broken if you go more than one back

### ISSUE THREAD

**Issue by patrickpereira** [TheOriginalJosh/nativescript-slides#85]
Hi Josh,

It works fine if I go higher in the slides, but if I go more than one back the slide doesn't update:

Example:

1. goToSlide(4) - works fine
2. goToslide(6) - works fine
3. goToSlide(5) - works fine
4. goToSlide(3) - broken, doesn't update the slide on any cases if you jump more than 1 index down.

**Comment by Universi** [comment]
This is a workaround which works fine for me : targeting the 0 index before targeting the destination index.
```
goToSlide(0);
goToSlide(indexTarget);
```

**Comment by TheOriginalJosh** [comment]
@patrickpereira I'm sorry I didn't get back to you. If this is still an issue please re-open
