### ISSUE TITLE
ClipBound with false value is not supported by android Angular2

### ISSUE THREAD

**Issue by AKNiazi** [TheOriginalJosh/nativescript-slides#86]
Hi,

I am running the example for angular2 provided in the description. But I keep getting following error.

clipToBounds with value false is not supported on Android. You can use this.android.getParent().setClipChildren(false) as an alternative

**Comment by irman** [comment]
Yes. I'm having the same issue. Although the app works on my emulator, I suspect this is the reason the app keep crashing on a real device, because this is the only warning I had when building.

**Comment by TheOriginalJosh** [comment]
I wonder if this is the offending code? 

https://github.com/TheOriginalJosh/nativescript-slides/blob/master/nativescript-slides.ts#L494

**Comment by irman** [comment]
@TheOriginalJosh It probably is. Can you update it? I've no experience doing a PR. XD

Thanks!

**Comment by TheOriginalJosh** [comment]
@irman will do tonight man.

**Comment by maddy2get** [comment]
@TheOriginalJosh has this been fixed yet? Really great plugin :-)
