### ISSUE TITLE
How to use this with angular2 , typescript, nativescript?

### ISSUE THREAD

**Issue by HenriqueMatias** [TheOriginalJosh/nativescript-slides#93]
Hi, @TheOriginalJosh ,

Thanks for this plugin. I was just thinking if there is a way to use this with nativescript.
Could you help me? is there a example?

**Comment by TheOriginalJosh** [comment]
Hey @HenriqueMatias I have one I specifically wrote for Angular 2 you can check it out at https://github.com/TheOriginalJosh/nativescript-ng2-slides
